version: '3.8'

services:
  backend:
    build: ./backend
    container_name: movie-explorer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - movie-explorer-network

  frontend:
    build: ./frontend
    container_name: movie-explorer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - movie-explorer-network

networks:
  movie-explorer-network:
    driver: bridge

volumes:
  backend-data: 